# Generated by Django 4.2.14 on 2024-08-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_student_id_student_name'),
        ('course', '0009_remove_course_assessment_method_course_teachers_and_more'),
        ('teacher', '0004_teacher_name'),
        ('classroom', '0002_alter_classroom_teacher_in_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='coursename',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='student.student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ManyToManyField(to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher_in_charge',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
