# Generated by Django 4.2.14 on 2024-08-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_department_alter_course_duration_and_more'),
        ('teacher', '0001_initial'),
        ('classperiod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classperiod',
            name='classcourse',
            field=models.ManyToManyField(to='course.course'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='classteacher',
            field=models.ManyToManyField(to='teacher.teacher'),
        ),
    ]
