# Generated by Django 4.2.14 on 2024-08-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_classroom_coursename_classroom_students_and_more'),
        ('classperiod', '0002_classperiod_classcourse_classperiod_classteacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classperiod',
            old_name='classcourse',
            new_name='coursename',
        ),
        migrations.RenameField(
            model_name='classperiod',
            old_name='classteacher',
            new_name='teacher',
        ),
        migrations.AddField(
            model_name='classperiod',
            name='class_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
            preserve_default=False,
        ),
    ]
