# Generated by Django 4.2.14 on 2024-08-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0003_rename_classcourse_classperiod_coursename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classperiod',
            name='class_instance',
        ),
    ]
