# Generated by Django 4.2.14 on 2024-08-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0003_alter_teacher_options_remove_teacher_teacher_id_and_more'),
        ('course', '0002_alter_course_department_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assessment_method',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Paper', 'Paper'), ('Group Work', 'Group Work')], default='Laptop', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_enrolled',
            field=models.ManyToManyField(related_name='courses', to='student.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
