# Generated by Django 4.2.14 on 2024-08-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_options_remove_teacher_teacher_id_and_more'),
        ('course', '0003_course_assessment_method_alter_course_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_in_charge',
            field=models.CharField(max_length=30),
        ),
    ]
