# Generated by Django 4.2.14 on 2024-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_teacher_name_alter_course_teacher_in_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_in_charge',
            field=models.CharField(max_length=10),
        ),
    ]
