# Generated by Django 4.2.14 on 2024-08-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_options_remove_teacher_teacher_id_and_more'),
        ('course', '0005_alter_course_teacher_in_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_in_charge',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
