# Generated by Django 4.2.14 on 2024-08-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_name'),
        ('course', '0008_alter_course_course_code_alter_course_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assessment_method',
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='teacher.teacher'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_enrolled',
        ),
        migrations.AddField(
            model_name='course',
            name='student_enrolled',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
