# Generated by Django 4.2.14 on 2024-08-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_course_assessment_method_course_teachers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_in_charge',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
