# Generated by Django 4.2.14 on 2024-08-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_name'),
        ('course', '0011_remove_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
