# Generated by Django 4.2.14 on 2024-08-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_teacher_in_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_in_charge',
        ),
    ]
