# Generated by Django 4.2.14 on 2024-08-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
