# Generated by Django 4.2.14 on 2024-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_options_remove_teacher_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
